services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: timesheet
    ports:
      - 5423:5432
    volumes:
      - timesheet_data:/var/lib/postgresql/data

  server:
    build:
      dockerfile: ./apps/server/Dockerfile
    ports:
      - 3201:3000
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/timesheet
    depends_on:
      - db

  dashboard:
    build:
      dockerfile: ./apps/dashboard/Dockerfile
    ports:
      - 3202:3000
    environment:
      NUXT_PUBLIC_SERVER_URL: http://server:3000
    depends_on:
      - server

volumes:
  timesheet_data:
