services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: timesheet
    ports:
      - 5423:5432
    volumes:
      - timesheet_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d timesheet"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  timesheet_data:
