services:
  db:
    image: postgres
    env_file:
      - ./apps/server/.env
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: timesheet
    ports:
      - 5423:5432
    volumes:
      - timesheet_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d timesheet"]
      interval: 5s
      timeout: 5s
      retries: 5

  server:
    build:
      dockerfile: ./apps/server/Dockerfile
    ports:
      - 3201:3100
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: timesheet
    depends_on:
      db:
        condition: service_healthy

  dashboard:
    build:
      dockerfile: ./apps/dashboard/Dockerfile
    ports:
      - 3202:3000
    depends_on:
      - server

volumes:
  timesheet_data:
