services:
  server:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: timesheet
    ports:
      - 5423:5432
    volumes:
      - timesheet_data:/var/lib/postgresql/data

volumes:
  timesheet_data:
